CREATE TABLE DONATION_LIST(
    DONA_NO         NUMBER            PRIMARY KEY, 
    DONA_TITLE      VARCHAR2(1000)    NOT NULL, 
    DONA_WRITER     VARCHAR2(20)      NOT NULL, 
    DONA_CONTENT    VARCHAR2(4000)    NOT NULL, 
    DONA_DATE       CHAR(10)          NOT NULL, 
    PA_AMOUNT       NUMBER            NOT NULL, 
    PA_LEVEL        VARCHAR2(20)      NOT NULL 
);
select count(*) as cnt from donation_List;

CREATE SEQUENCE DONA_SEQ;

SELECT * FROM DONATION_LIST;

INSERT INTO DONATION_LIST VALUES(DONA_SEQ.NEXTVAL,'아이들아!','서준식','큰돈은 아니지만 이돈으로 행복했으면 좋겠다!',TO_CHAR(SYSDATE,'YYYY-MM-DD'),10000000,'개인');
INSERT INTO DONATION_LIST VALUES(DONA_SEQ.NEXTVAL,'아이들아!','백지흠','나혼자 배부른것보다 여러분과 배부르고싶어요',TO_CHAR(SYSDATE,'YYYY-MM-DD'),5000000,'기업');
INSERT INTO DONATION_LIST VALUES(DONA_SEQ.NEXTVAL,'아이들아!','박성우','커서 꼭 좋은 어른이 되렴!',TO_CHAR(SYSDATE,'YYYY-MM-DD'),2000600,'학교 및 단체');
INSERT INTO DONATION_LIST VALUES(DONA_SEQ.NEXTVAL,'아이들아!','강은현','애들아 커서 행복하고, 꽃길만 걸으렴',TO_CHAR(SYSDATE,'YYYY-MM-DD'),1000000,'개인');
INSERT INTO DONATION_LIST VALUES(DONA_SEQ.NEXTVAL,'아이들아!','양원주','전 미래를 위해 지금 이순간 후원을 합니다',TO_CHAR(SYSDATE,'YYYY-MM-DD'),2700000,'기업');
INSERT INTO DONATION_LIST VALUES(DONA_SEQ.NEXTVAL,'아이들아!','홍수연','여러분 저랑 같이 후원합시다!!!!!',TO_CHAR(SYSDATE,'YYYY-MM-DD'),6060000,'학교 및 단체');

COMMIT;

INSERT INTO DONATION_LIST VALUES(DONA_SEQ.NEXTVAL,'제목','작성자','내용',TO_CHAR(SYSDATE,'YYYY-MM-DD'),500000,'개인');

SELECT * FROM(SELECT ROWNUM AS RNUM, N.*FROM(SELECT * FROM Donation_List ORDER BY dona_NO DESC)N) WHERE RNUM BETWEEN 1 AND 10;

SELECT DONA_NO,DONA_TITLE,DONA_WRITER,DONA_CONTENT,DONA_DATE,PA_AMOUNT,PA_LEVEL FROM Donation_List ORDER BY dona_NO DESC;

SELECT * FROM DONATION_LIST;
SELECT * FROM MEMBER;

DROP TABLE MEMBER;
DROP SEQUENCE MEMBER_SEQ;

SELECT SUM("PA_AMOUNT") FROM DONATION_LIST;

SELECT TO_CHAR(PA_AMOUNT,'999,999,999') FROM DONATION_LIST;
COMMIT;






--후원과정에서 정보저장
CREATE TABLE DONATION(
    PA_NO       NUMBER          NOT NULL,
    PATRON      VARCHAR2(20)    NOT NULL, 
    PA_USE      NUMBER          NOT NULL, 
    PA_KIND     NUMBER          NOT NULL, 
    PA_PHONE    CHAR(11)        NOT NULL, 
    PA_EMAIL    VARCHAR2(20)    NOT NULL, 
    PA_PW       VARCHAR2(30)    NOT NULL,
    PA_PRICE    NUMBER          NOT NULL
);
DROP TABLE DONATION;
DROP SEQUENCE PA_SEQ;

SELECT * FROM DONATION;

CREATE SEQUENCE PA_SEQ;




----------------------------------------
--회원--
CREATE TABLE MEMBER(
    MEMBER_NO NUMBER PRIMARY KEY,
    MEMBER_ID VARCHAR2(20) UNIQUE,
    MEMBER_PW VARCHAR2(30) NOT NULL,
    MEMBER_NAME VARCHAR2(20) NOT NULL,
    MEMBER_ADDR VARCHAR2(100),
    MEMBER_EMAIL VARCHAR2(100)
);

ALTER TABLE MEMBER MODIFY (MEMBER_EMAIL DEFAULT 'EmailID@Domain.co.kr');
UPDATE MEMBER SET MEMBER_EMAIL = DEFAULT WHERE MEMBER_NO=21;
SELECT * FROM DONATION_LIST;
SELECT * FROM MEMBER;
ALTER TABLE MEMBER ADD PHONE VARCHAR(13);
ALTER TABLE MEMBER DROP COLUMN PHONE;
insert into member values(MEMBER_SEQ.NEXTVAL,'test99','1234','서준식','서울',default,'01028747801');

DELETE FROM MEMBER WHERE MEMBER_NO=4;
COMMIT;

commit;
select * from member where member_id='test00' and member_pw='1234';
--공지사항--
CREATE TABLE NOTICE(
    NOTICE_NO NUMBER PRIMARY KEY,
    NOTICE_TITLE VARCHAR2(20) NOT NULL,
    NOTICE_WRITER VARCHAR2(20) REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE,
    NOTICE_CONTENT VARCHAR2(4000) NOT NULL,
    NOTICE_DATE CHAR(10) NOT NULL,
    FILENAME VARCHAR2(500),
    FILEPATH VARCHAR2(500)
);


CREATE SEQUENCE NOTICE_SEQ;
select * from notice1 where notice_no=81;
SELECT * FROM NOTICE1;
SELECT * FROM NOTICE;
SELECT * FROM ADMIN;
SELECT * FROM PRODUCT;
